const cloudinary = require('cloudinary').v2;
const fs = require('fs');
const path = require('path');

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET
});

/**
 * Uploads a file locally to a temporary directory.
 * @param {string} filePath - Local absolute path to the file
 * @returns {Promise<{ filename: string }>}
 */
const uploadPdf = async (filePath) => {
  try {
    const exportsDir = path.join(__dirname, '../../storage/temp/exports');
    if (!fs.existsSync(exportsDir)) {
      fs.mkdirSync(exportsDir, { recursive: true });
    }

    const fileName = path.basename(filePath);
    const destination = path.join(exportsDir, fileName);
    
    // Copy the file to the temp directory
    fs.copyFileSync(filePath, destination);
    
    // Delete local temp file generated by PDFKit
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
    
    return {
      filename: fileName,
    };
  } catch (error) {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
    throw new Error('Failed to save file locally: ' + error.message);
  }
};

/**
 * Gets the absolute path to a temporary PDF and ensures it exists.
 * @param {string} filename 
 * @returns {string|null} Path to the file if it exists, otherwise null
 */
const getTempPdfPath = (filename) => {
  // Prevent path traversal
  if (filename.includes('/') || filename.includes('\\') || filename.includes('..')) {
    return null;
  }
  
  const filePath = path.join(__dirname, '../../storage/temp/exports', filename);
  if (fs.existsSync(filePath)) {
    return filePath;
  }
  return null;
};

module.exports = {
  uploadPdf,
  getTempPdfPath
};
